### PR TITLE
add simplified chinese translation

### PR DESCRIPTION
**Pull request by AlbertWh1te**

### CODE REVIEW

**Comment by eabz** [comment]
@AlbertWh1te Thanks!!!

Pls add your FTM address to get a tip

**Comment by AlbertWh1te** [comment]
Thanks. 
My FTM address is 
```
0x941169FFF3C353BE965e3f34823eeA63b772219c
```
Please let me know if there is anything that I can help with!

**Comment by eabz** [comment]
Sent 30 FTM.

We always need someone that can constantly bring upgrades to the codebase. 
If you are familiar with React, Web3 deployment feel free to submit a PR.

**Comment by AlbertWh1te** [comment]
Thank you very much!

**Pull request merged**
